# UI Colors
COLOR_BACKGROUND = "#1e1e1e"
COLOR_DARK_BACKGROUND = "#191919"

# Light Colors
COLOR_GREEN = "#50C878"
COLOR_AQUA = "#17BADD"
COLOR_BLUE = "#448aff"
COLOR_YELLOW = "#DABA0A"
COLOR_PINK = "#FF007F"
COLOR_RED = "#D24141"
COLOR_PURPLE = "#9C50B6"

# Dark Colors
COLOR_DARK_GREEN = "#50A688"
COLOR_DARK_AQUA = "#6B9EAB"
COLOR_DARK_BLUE = "#3779ff"
COLOR_DARK_YELLOW = "#B39908"
COLOR_DARK_PINK = "#DE5D83"
COLOR_DARK_RED = "#CC0000"
COLOR_DARK_PURPLE = "#653475"

COLORS = [COLOR_GREEN, COLOR_AQUA, COLOR_BLUE, COLOR_YELLOW, COLOR_PINK, COLOR_RED, COLOR_PURPLE, \
COLOR_DARK_GREEN, COLOR_DARK_AQUA, COLOR_DARK_BLUE, COLOR_DARK_YELLOW, COLOR_DARK_PINK, COLOR_DARK_RED, COLOR_DARK_PURPLE]